[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y libzip-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libonig-dev libxml2-dev",
    "docker-php-ext-configure gd --with-freetype --with-jpeg",
    "docker-php-ext-install zip gd exif pdo_mysql mbstring xml curl fileinfo openssl json"
]

[phases.install]
cmds = [
    "composer install --no-interaction --optimize-autoloader --no-scripts"
]

[phases.build]
cmds = [
    "npm install",
    "npm run build"
]

[phases.start]
cmd = "php-fpm"